version: '3.8'

services:
    backend :
      build : 
        context : . 
        dockerfile : Dockerfile.backend
      ports : 
      - "5001:5001"
      restart : unless-stopped
    
    frontend : 
       build : 
         context : .
         dockerfile : Dockerfile.frontend
       ports :
        - "5713:80"
       restart : unless-stopped

      