name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request :
    branches : ["master"]
       
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Build and push backend image
        run: |
          docker build -f Dockerfile.backend -t ${{ secrets.DOCKER_USERNAME }}/lyvo-messenger:chat-backend .
          docker push ${{ secrets.DOCKER_USERNAME }}/lyvo-messenger:chat-backend

      - name:  Build and push frontend image
        run: |
          docker build -f Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/lyvo-messenger:chat-frontend .
          docker push ${{ secrets.DOCKER_USERNAME }}/lyvo-messenger:chat-frontend